# Generated by Django 4.1.2 on 2022-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicefifteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField(max_length=10, verbose_name='Pay ID')),
                ('date', models.DateTimeField(verbose_name='Date and Time')),
            ],
        ),
    ]
